deleting excessed free spaces
kottans/mock-repo pull request #1027
Opened 2022-08-11 15:35 UTC by anna-dao

just deleted some free spaces to make the file more accurate.

2022-08-11 16:39 UTC, suchov commented
Yes, but also add some free spaces??? :D
Can you pls check the lines changed?

2022-08-12 12:05 UTC, suchov requested changes

2022-08-12 12:05 UTC, suchov commented on README.md
> -
no need to do this, pls leave only the desired lines editing

2022-08-13 15:16 UTC, anna-dao commented
seems I added some free spaces too, will delete them and pull it one more time.. 
sorry!!

2022-08-17 05:58 UTC, suchov commented
No worries, it's a play with file at the end of the day ;)

2022-08-26 16:20 UTC, closed without merging