Greeting to Kottans was added. Shared my repo.
kottans/mock-repo pull request #1037
Opened 2022-08-12 11:11 UTC by YershovArt

Hi kottans . This is my first pull request.

2022-08-12 16:13 UTC, suchov requested changes

2022-08-12 16:13 UTC, suchov commented on README.md
> -### I'm Valentyn.
pls don't change the lines you are not working with, check the discord if you need help

2022-08-15 18:45 UTC, YershovArt commented
Conflict markers was deleted.

2022-08-15 19:46 UTC, suchov approved these changes

2022-08-15 19:46 UTC, merged