Added greetings & image <3
kottans/mock-repo pull request #1048
Opened 2022-08-13 02:27 UTC by lometari

2022-08-13 11:51 UTC, artem-trubin commented
Hi and welcome! Can you please post the image with Markdown syntax, not with an HTML tag?

2022-08-13 15:27 UTC, suchov requested changes

2022-08-13 15:27 UTC, suchov commented on README.md
> +<img src="https://github.com/lometari/mock-repo/raw/firstStep/gif/belovedCat.jpg" width="70%" margin="auto">
no HTML tegs in markdown pls 
you can read more about hot to do it here -> https://www.markdownguide.org/basic-syntax/

2022-08-17 18:55 UTC, lometari commented
Hi! Should I need to change something else?

2022-08-17 22:51 UTC, merged

2022-08-17 22:51 UTC, suchov commented
Hi, nope, looks like everything is amazing.