second pull-request by sshapran
kottans/mock-repo pull request #1110
Opened 2022-08-23 00:30 UTC by sshaprans

2022-08-23 14:07 UTC, suchov requested changes

2022-08-23 14:07 UTC, suchov commented on README.md
>  # Kottans-frontend
Nicely done.
The only request - can you move your changes(lines) under those ones - that points to the Discord with the help chat...?

2022-08-24 23:06 UTC, sshaprans commented
first the attempt, then the documentation

2022-08-28 09:15 UTC, suchov approved these changes

2022-08-28 09:15 UTC, suchov commented
Looks great! 🚀

2022-08-28 09:16 UTC, merged