My first pull request.
kottans/mock-repo pull request #1164
Opened 2022-09-22 13:36 UTC by AnnaLozovytska

I completed the first Git and GitHub Intro task. I did my first pull request

2022-09-23 11:28 UTC, suchov commented on README.md
> +
Too many changes +299 −175 adding/removing for couple lines change ;)

2022-09-23 11:30 UTC, suchov requested changes

2022-09-23 11:30 UTC, suchov commented on README.md
> -* __git init, git clone, git status__ - их, и многие другие я буду точно использовать в будущем
Looks like you need to config your IDE.

2022-09-23 13:52 UTC, suchov commented
@AnnaLozovytska it feels like you struggle a bit. You need to check what changes you are suggesting to do with your "merge request" https://github.com/kottans/mock-repo/pull/1164/files - here is a good place to see them.
You can find things that can help you at https://discord.gg/XqNT2mGJ

2022-09-23 13:58 UTC, AnnaLozovytska commented
I already understood what the mistake was. I opened the file with VScode and it adds the lines. I'm fixing it now. thank you

2022-09-24 09:52 UTC, suchov approved these changes

2022-09-24 09:52 UTC, suchov commented
Really nice, great work @AnnaLozovytska !

2022-09-24 09:52 UTC, merged