Update readme
kottans/mock-repo pull request #423
Opened 2020-10-09 18:45 UTC by youhymuk

- Fixed a typo;
- Added greeting for kottans;

2020-10-09 19:07 UTC, miroslav-kolomiets requested changes
Hello! Nice job, but your pull request affects other people's code. This may be due to your editor's auto-formatting. Can you please recheck it? Thanks.

2020-10-09 19:15 UTC, miroslav-kolomiets commented on README.md
> +*This was an intentionally misspelled phrase*
Pay special attention to this phrase :)

2020-10-10 07:42 UTC, youhymuk commented
Hi! Is it correct now?

2020-10-10 17:41 UTC, youhymuk commented
I can't understand what the problem is. I've already resolved the conflict several times...

2020-10-10 18:09 UTC, miroslav-kolomiets commented on README.md
> +and [git](https://github.com/Kottans/git-course) courses.
There are a few things that need to be improved. There is no need to remove spaces where text is added by other students. This applies to this place and to similar ones below in the document.

2020-10-10 18:09 UTC, miroslav-kolomiets commented on README.md
> +<<<<<<< HEAD
This got into the commit due to an incorrectly fixed conflict, you need to remove it. And clean up the code below.

2020-10-10 18:12 UTC, miroslav-kolomiets commented
> I can't understand what the problem is. I've already resolved the conflict several times...

This is normal. This is due to the fact that other PRs were merged into the branch.

2020-10-10 18:30 UTC, youhymuk commented
I really hope that this time I did everything right)

2020-10-10 18:45 UTC, miroslav-kolomiets commented on README.md
> +***
```suggestion
***

### Hello, kottans:)
My name is [Dima](https://github.com/youhymuk) and I'm glad to study here with you.
I wish you all success!
![kottan](gif/cat-headshot.gif)

***
```

2020-10-10 18:51 UTC, miroslav-kolomiets commented
> I really hope that this time I did everything right)

Not yet. You miss this comment https://github.com/kottans/mock-repo/pull/423#discussion_r502816367

In fact, all that should be in the PR is:

```
### Hello, kottans:)
My name is [Dima](https://github.com/youhymuk) and I'm glad to study here with you.
I wish you all success!
![kottan](gif/cat-headshot.gif)
```

 And your file - cat-headshot.gif.

There should be no other changes;)

2020-10-10 22:04 UTC, Temu4 requested changes

2020-10-10 22:04 UTC, Temu4 commented on README.md
> +Hello!
Hi Dima! 
Your code if good! But you a little bit change previous code in this file (even if it just a `space` or `tab`)
I guess the main reason you did changes like this
![Screenshot](https://iili.io/24Svls.md.png)
is that you use some autoFormat settings in you redactor/IDE. You can try to turn off this behaviour (at least during this task).
P.S. To roll back in repo files history you, for example, can use `git log` and `git checkout commitSHA`

2020-10-11 09:12 UTC, youhymuk commented
Hi! Thank you for your review guys! I'm truly hoping that everything is ok at this time...

2020-10-11 09:21 UTC, youhymuk commented
But I already see there is the same problem... I don't know what is wrong, because I use default settings in WebStorm

2020-10-11 09:32 UTC, youhymuk commented
I used  the hard reset to d648791, before adding my code

2020-10-12 09:22 UTC, Temu4 commented
@youhymuk the problem is not with your code, but with settings in IDE you use (WebShtorm if I'm right).

Auto-formating is really great tool! 👍  But when you collaborate with other people, and work on the same files, it can add no needed changes to the files.

You can **disable auto-formatting** code (at least for this PR) [--> see this <--](https://stackoverflow.com/questions/2977324/disable-reformatting-code-when-saving-files)

2020-10-13 12:12 UTC, youhymuk commented
I can't understand how it works, because I have disabled autoformatting in WS as you said to me, but it was the same problem...And now I did my changes in Sublime Text without any formatting.  How can I see there is a problem only in one place now.

2020-10-13 12:18 UTC, nazmariam commented on README.md
> +![Image of DevCat](https://www.nexmo.com/wp-content/uploads/2016/08/dx-jamie-comic.jpg)
Please don't make changes in previous code, it'll make conflicts for you and another students.
And also could you check image path? 
<img width="809" alt="Screenshot 2020-10-13 at 15 17 20" src="https://user-images.githubusercontent.com/14895118/95859483-5d1e6e00-0d67-11eb-8af9-5ce53df0dbac.png">

2020-10-13 13:04 UTC, Temu4 approved these changes
LGTM! 👍 

P.S.
The image will appear after merge.

2020-10-13 16:39 UTC, nazmariam approved these changes

2020-10-13 19:23 UTC, nazmariam approved these changes
But do you think force push is a good idea? :)

2020-10-13 19:27 UTC, youhymuk commented
> But do you think force push is a good idea? :)

Hm, does it have negative consequences on this case?

2020-10-13 19:33 UTC, nazmariam commented
> > But do you think force push is a good idea? :)
> 
> Hm, does it have negative consequences on this case?

No, in this case I would not give approval. Just kindly reminder not to abuse force pushes unnecessarily

2020-10-13 19:41 UTC, youhymuk commented
> > > But do you think force push is a good idea? :)
> > 
> > 
> > Hm, does it have negative consequences on this case?
> 
> No, in this case I would not give approval. Just kindly reminder not to abuse force pushes unnecessarily

Ok, I'll remember about it, thanks!)

2020-10-14 10:58 UTC, miroslav-kolomiets approved these changes
Now it's good to go, good job!

2020-10-14 10:58 UTC, merged