Add my information about Git.
kottans/mock-repo pull request #446
Opened 2020-10-13 17:31 UTC by lisnyak-o

2020-10-13 17:50 UTC, miroslav-kolomiets requested changes
Looks great! But you make some changes in bottom of the file, maybe add a new line, you should not change other people code ;)
<img width="1335" alt="Снимок экрана 2020-10-13 в 8 48 15 PM" src="https://user-images.githubusercontent.com/14906260/95897130-b1d8dd80-0d95-11eb-9360-d331b0f899ca.png">

2020-10-13 20:34 UTC, lisnyak-o commented
Thanks @miroslav-kolomiets , I decided conflict, where`re maked mistakes.

2020-10-17 15:29 UTC, miroslav-kolomiets requested changes
Now it's good, but you need to resolve conflict in your branch.

2020-10-17 22:11 UTC, lisnyak-o commented
I merge base branch and pull new changes in this project for my fork.

2020-10-20 08:43 UTC, Temu4 requested changes

2020-10-20 08:43 UTC, Temu4 commented on README.md
>  # Hi Everyone =)
Please try to not change other people's code.

2020-10-20 08:43 UTC, Temu4 commented on README.md
> ----
As well as here ⬆️

2020-10-23 08:36 UTC, lisnyak-o commented
Guys, please see it`s right made ?

It was : 
![123](https://user-images.githubusercontent.com/20680156/96975977-eaaa4c80-1523-11eb-9d87-af8ff66ef4a0.png)
Result : 
![321](https://user-images.githubusercontent.com/20680156/96975981-ec741000-1523-11eb-9bb2-da245fa561a2.png)

2020-10-27 08:34 UTC, miroslav-kolomiets requested changes

2020-10-27 08:34 UTC, miroslav-kolomiets commented on README.md
> +
Simply, the PR should contain nothing but these lines.

2020-10-27 08:34 UTC, miroslav-kolomiets commented on README.md
> +
It shouldn't be.

2020-10-27 08:34 UTC, miroslav-kolomiets commented on README.md
> +
It shouldn't be too.

2020-10-27 08:34 UTC, miroslav-kolomiets commented on README.md
> ----
It shouldn't be too.

2020-10-28 18:03 UTC, babayK0 commented
@lisnyak-o resolve conflicts please)

2020-10-29 11:12 UTC, lisnyak-o commented
I leave empty line to the end for comment, but when I push my file it's line haven't, why  it's happend?

![Screenshot_1](https://user-images.githubusercontent.com/20680156/97561065-41ae9680-19e8-11eb-891f-c0794a22113d.png)
![Screenshot_2](https://user-images.githubusercontent.com/20680156/97561070-43785a00-19e8-11eb-8018-8ebea5529e6b.png)

2020-11-01 19:46 UTC, Temu4 commented
Hey @lisnyak-o !
I still see a lot of code changes with you commits.

I hope you can do smth like these: 
1. Turn off auto-format settings in your code redactor/IDE.
2. Roll back to initial state of this branch (before your changes)
3. Pull the latest changes from origin repo
4. Add you code

If you need more info, please, fill free to touch me 😸

2020-11-05 20:28 UTC, lisnyak-o commented
I hope everything worked out.
  What I did ?
1) git reset --hard HEAD
2) git fetch upstream
3) Added my own text at the end of the file, added a photo, then did => commit
4) git pull master
5) Solved the conflict. Accepted the current changes, and canceled the incoming (from the pull master).
6) git push

![image](https://user-images.githubusercontent.com/20680156/98292884-1f071980-1fb6-11eb-98f2-a6dd99869b2f.png)
Why this line changed to the same line I don't know. I didn't touch her!

2020-11-06 08:02 UTC, lisnyak-o commented
I'm already confused. Can I create a new PR? After all, I can't push a rollback via reset to the server.
And how then to solve this situation, I can not even imagine.

2020-11-06 10:56 UTC, closed without merging

2020-11-06 10:57 UTC, lisnyak-o commented
I created a new PR.