Hello (and a cat pic) from new student
kottans/mock-repo pull request #460
Opened 2020-10-18 13:38 UTC by ses3332002

2020-10-18 13:48 UTC, nazmariam approved these changes

2020-10-18 13:48 UTC, nazmariam commented on README.md
> +![cat-image](assets/images/shakespeare.jpg)
Hi Sergey and Shakespeare! Good job!

2020-10-19 16:59 UTC, Temu4 approved these changes
Looks good to me! 👍

2020-10-27 23:03 UTC, Temu4 requested changes
Hey, well done! 😃 
Unfortunately you haven't only added your greeting but made changes in many places in the readme file.
I guess you have some auto-formatting settings like **Format On Save** in you redactor/IDE. And when you save file it automatic formats. 
Try to disable it, restore readme for initial version and add your greetings again.

Please, fill free to ping me if you need more info 🐱

2020-10-31 19:39 UTC, ses3332002 commented on README.md
> +and [git](https://github.com/Kottans/git-course) courses.
Please check my new attempt

2020-11-02 21:03 UTC, ses3332002 commented on README.md
> +![Cat](assets/images/CatFromLviv.jpg)
Is there another whitespace deleted?
I turned off this option in my editor, so it shouldn't have done it.

2020-11-02 21:03 UTC, miroslav-kolomiets approved these changes
Nice work! But for the future it is better to avoid force-push ;)

2020-11-02 21:04 UTC, merged

2020-11-02 21:15 UTC, ses3332002 commented
Thank you so much!
I've learned that I need to put empty lines at the end of files, and that
my editor should not edit other people's lines, removing final spaces from
there.
But what was my last mistake? Why GitHub shows that some foreign line was
deleted and then added again?

пн, 2 нояб. 2020 г. в 23:04, Miroslav Kolomiets <notifications@github.com>:

> *@miroslav-kolomiets* approved this pull request.
>
> Nice work! But for the future it is better to avoid force-push ;)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kottans/mock-repo/pull/460#pullrequestreview-521990684>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEYN7XXEZUXU7AXAOYYPWU3SN4NEVANCNFSM4SVC54BQ>
> .
>