This was an intentionaly mispelld phrase
kottans/mock-repo pull request #486
Opened 2020-10-21 22:36 UTC by laneleka

2020-10-22 09:55 UTC, miroslav-kolomiets requested changes
Hi! Well done! But your code affects other people's code. Possibly due to IDE settings.

2020-10-23 21:43 UTC, miroslav-kolomiets requested changes
Well done! But you don't have to affect others peoples code. I mean line 1607, 1612, 1613.

2020-10-23 21:44 UTC, miroslav-kolomiets requested changes

2020-10-23 21:44 UTC, miroslav-kolomiets commented on README.md
> +---
You only need to keep these changes.

2020-10-23 22:04 UTC, laneleka commented on README.md
> +---
I fixed, thanks.

2020-10-24 11:07 UTC, miroslav-kolomiets approved these changes
Well done!

2020-10-24 11:07 UTC, merged