Update README.md
kottans/mock-repo pull request #505
Opened 2020-10-26 19:43 UTC by mitko1717

i added my greeting

2020-10-27 14:58 UTC, Temu4 requested changes
Hello!
Good job! 🐱 
But can you get the latest changes and fix conflicts?

2020-10-27 14:58 UTC, Temu4 commented on README.md
> +I'm glad I found ur course!
you probably want to write `our`?

2020-10-27 18:44 UTC, babayK0 commented
@mitko1717 Please, fix conflicts

2020-10-27 21:59 UTC, lenadgit commented
How to resolve conflicts 
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

2020-10-29 11:57 UTC, babayK0 commented
@mitko1717 Fix conflicts, and i will approve :smiley:

2020-10-29 20:01 UTC, mitko1717 commented
i really don't understand what conflicts u r talking about


чт, 29 окт. 2020 г. в 13:58, Bohdan Kovalchuk <notifications@github.com>:

> @mitko1717 <https://github.com/mitko1717> Fix conflicts, and i will
> approve 😃
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kottans/mock-repo/pull/505#issuecomment-718705819>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO6WYBAFWNUCTJTUX66ZWA3SNFKE5ANCNFSM4S72URTQ>
> .
>

2020-10-29 21:39 UTC, babayK0 commented
@mitko1717 you have conflicts in README.md

https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts

2020-10-29 21:41 UTC, babayK0 commented
You need pull changes from remote, resolve conflicts and push your code again.

2020-11-01 19:31 UTC, Temu4 commented
@mitko1717 since that time when you've forked origin repo and added your changes some people made their own changes and pushed them.
So you can just pull the latest updates from the original repo and fix conflicts.
If you need more info, plz, fill free to touch me 😸

2020-11-02 20:39 UTC, mitko1717 commented
hi. today i ended one more stage and wanted to make push from my local to
add the folder with screenshots, but something went wrong.
i got this message from my terminal:

git push

To https://github.com/mitko1717/kottans-frontend/

 ! [rejected]        main -> main (non-fast-forward)

error: failed to push some refs to '
https://github.com/mitko1717/kottans-frontend/'

hint: Updates were rejected because the tip of your current branch is behind

hint: its remote counterpart. Integrate the remote changes (e.g.

hint: 'git pull ...') before pushing again.

hint: See the 'Note about fast-forwards' in 'git push --help' for details.


then i tried to pull from remote, but

git pull

error: Your local changes to the following files would be overwritten by
merge:

  mock-repo

then i tried to make pull of the forked repo (mock-repo)

i got this:

$ git pull https://github.com/mitko1717/mock-repo

warning: no common commits

remote: Enumerating objects: 2553, done.

remote: Total 2553 (delta 0), reused 0 (delta 0), pack-reused 2553

Receiving objects: 100% (2553/2553), 167.40 MiB | 874.00 KiB/s, done.

Resolving deltas: 100% (1181/1181), done.

From https://github.com/mitko1717/mock-repo

 * branch            HEAD       -> FETCH_HEAD

fatal: refusing to merge unrelated histories


what's wrong? plz help me. ive already pushed and pulled some files.
everything was good

вс, 1 нояб. 2020 г. в 21:32, Artem Vorobiov <notifications@github.com>:

> @mitko1717 <https://github.com/mitko1717> since that time when you've
> forked origin repo and added your changes some people made their own
> changes and pushed them.
> So you can just pull the latest updates from the original repo and fix
> conflicts.
> If you need more info, plz, fill free to touch me 😸
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kottans/mock-repo/pull/505#issuecomment-720139454>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO6WYBGFUWJDPVN3JF6C4H3SNWZTPANCNFSM4S72URTQ>
> .
>

2020-11-02 23:12 UTC, babayK0 approved these changes
:+1:

2020-11-02 23:13 UTC, merged