Roophee is on the board
kottans/mock-repo pull request #511
Opened 2020-10-28 15:18 UTC by Roophee

Roophee join to the mock-repo. White some words about myself. Add image.

2020-10-28 15:28 UTC, miroslav-kolomiets requested changes

2020-10-28 15:28 UTC, miroslav-kolomiets commented on README.md
> +I`mg glad to join this community and stsrt this trip!!!
```suggestion
I'm glad to join this community and start this trip!!! 
```

2020-10-28 17:44 UTC, babayK0 commented
@Roophee 
Resolve conflicts, please

2020-10-29 11:29 UTC, Roophee commented on README.md
> +I`mg glad to join this community and stsrt this trip!!!
@miroslav-kolomiets fixed typo, thanks

2020-10-29 11:30 UTC, Roophee commented
@babayK0 done, thanks

2020-10-29 11:56 UTC, babayK0 approved these changes
@Roophee Nice catbird !
 :bird: + :cat: = :heart:

2020-10-29 11:56 UTC, merged