Hello I'm Max
kottans/mock-repo pull request #515
Opened 2020-10-31 23:50 UTC by phpslonuk

I'm with you, finished the course Version Control with Git

2020-11-01 18:13 UTC, babayK0 commented on README.md
Add your text in the end of README.md

2020-11-01 18:13 UTC, babayK0 requested changes
Add your text in the end of README.md

2020-11-03 00:03 UTC, phpslonuk commented
Changed README.md

2020-11-03 00:13 UTC, babayK0 requested changes

2020-11-03 00:13 UTC, babayK0 commented on README.md
> +
Seems like you forgot to delete vscode(or other editors') "conflict pointers"

2020-11-03 00:13 UTC, babayK0 commented on README.md
> +=======
Here same

2020-11-03 00:13 UTC, babayK0 commented on README.md
> +>>>>>>> master
Same

2020-11-03 00:24 UTC, phpslonuk commented
Deleted 'conflict pointers'

2020-11-03 00:50 UTC, babayK0 approved these changes

2020-11-03 13:58 UTC, babayK0 approved these changes

2020-11-03 13:58 UTC, merged