Add new greeting.
kottans/mock-repo pull request #548
Opened 2020-11-11 16:32 UTC by Ant-C-tech

2020-11-11 19:41 UTC, lenadgit requested changes
Good job!  But if you look at your file  https://github.com/kottans/mock-repo/pull/548/files  you will see the highlighted lines in red. It happened because your code-editor autoformatted lines (indentations, etc), and we can not merge it. Could you please fix it? How to resolve this issue - was mentioned here 
https://github.com/kottans/mock-repo/pull/460#pullrequestreview-518209900

2020-11-12 10:55 UTC, Ant-C-tech commented
Please, check my greeting)

2020-11-12 19:45 UTC, miroslav-kolomiets requested changes
Hi! Good job! But you have a typo, that's why your link looks like
<img width="1247" alt="Снимок экрана 2020-11-12 в 9 43 51 PM" src="https://user-images.githubusercontent.com/14906260/98988509-6ea69180-2530-11eb-9f84-5558b5b27648.png">

2020-11-12 19:45 UTC, miroslav-kolomiets commented on README.md
> +My name is [Anton] (https://github.com/Ant-C-tech). First part of education course "Version Control with Git" and especially "learngitbranching.js.org" was very useful for me and now I'm excited to c
```suggestion
My name is [Anton](https://github.com/Ant-C-tech). First part of education course "Version Control with Git" and especially "learngitbranching.js.org" was very useful for me and now I'm excited to continue adventure with your wonderful interesting community.
```

2020-11-13 21:55 UTC, lenadgit commented
Good. But as you see - your file now has a conflict. If you  look at the file, you will see that other participant added changes after your greeting 
https://github.com/kottans/mock-repo/pull/548/conflicts
How to resolve it:
Type at command line:
- git pull origin main
- git push
You can get new changes (Anastasia's greeting) and push your changes again

2020-11-14 08:52 UTC, miroslav-kolomiets approved these changes
Nice job!

2020-11-14 08:52 UTC, merged

2020-11-14 09:28 UTC, Ant-C-tech commented
Can you help me to understand this moment? In order if there are many pull requests a day you can merge only one of them, because others would be need some revision? When I made my last  pull request there was no commit #550. If I understand it right, commit #550 was in queue for merge. I would like to understand how can one do merging without revision all the queue of pull requests? It would help me to understand how can I do such things properly. Thank you.

2020-11-14 11:13 UTC, miroslav-kolomiets commented
> Can you help me to understand this moment? In order if there are many pull requests a day you can merge only one of them, because others would be need some revision? When I made my last pull request there was no commit #550. If I understand it right, commit #550 was in queue for merge. I would like to understand how can one do merging without revision all the queue of pull requests? It would help me to understand how can I do such things properly. Thank you.

If I understand your question correctly:

These things do not depend on each other, only if the changes concerned the same places in the code. In this case, you need to resolve the conflict. In other cases, commits, with merge, do not affect each other and doesn't need some special revision.

2020-11-14 13:01 UTC, Ant-C-tech commented
Thank you for the answer. I mean, for example, today you have 20 commits and each wants to start on line 1825 (last line in Readme. md). If you merge one of them other commits need revision because line 1825  is now occupied. This case for me is interesting.