change readme file
kottans/mock-repo pull request #715
Opened 2022-07-25 14:59 UTC by AlekseyGusar

2022-07-26 20:33 UTC, artem-trubin commented
Hi! Please check "Files changed" tab and try to resolve the problem. (tip: autoformatter)

2022-07-27 17:45 UTC, AlekseyGusar commented
> Hi! Please check "Files changed" tab and try to resolve the problem. (tip: autoformatter)

I have relolved all conflicts

2022-07-31 16:50 UTC, artem-trubin commented
Hey, your problem wasn't the conflict. Please pay more attention to comments. Check "Files changed" tab.

2022-08-11 19:00 UTC, suchov requested changes

2022-08-11 19:00 UTC, suchov commented on README.md
> -
do you need this line removing?

2022-08-11 19:00 UTC, suchov commented on README.md
> +
and adding those one's?

2022-08-11 19:00 UTC, suchov commented on README.md
> -_________________________________________________
?

2022-08-13 09:00 UTC, closed without merging