Solution
kottans/mock-repo pull request #857
Opened 2022-08-01 11:38 UTC by student1232354

2022-08-01 11:39 UTC, student1232354 commented
Перевірка

2022-08-01 11:39 UTC, student1232354 commented
все наче правильно

2022-08-01 14:19 UTC, serentinos commented
Привіт! Молодець, що правильно кинув Pull Request, але по завданню, тобі потрібно внести тільки зміни в файлі README.md, але не додавати нові файли типу test.py:)

2022-08-05 16:28 UTC, A-Ostrovnyy commented
@student1232354 please check comments)

2022-08-11 19:04 UTC, suchov requested changes

2022-08-11 19:04 UTC, suchov commented on test.py
> +print("hello f#cking repository");
wow, print? :D test.py?
that's something new, but we probably need just a couple lines in a readme.md file

2022-08-14 13:14 UTC, closed without merging