Dasha
kottans/mock-repo pull request #881
Opened 2022-08-02 11:09 UTC by DanyaBu

Willing to say hi to guys starting this awesome course

2022-08-02 17:52 UTC, artem-trubin commented
Hi! Can you please use Markdown syntax to format text, not HTML?

2022-08-03 05:35 UTC, A-Ostrovnyy commented
@DanyaBu avoid using HTML tags in markdown use [this resource](https://codingnconcepts.com/markdown/markdown-vs-html/) to convert your HTML to markdown.

2022-08-05 10:20 UTC, DanyaBu commented
> Hi! Can you please use Markdown syntax to format text, not HTML?

Done
Thank you in advance)

2022-08-05 10:22 UTC, A-Ostrovnyy requested changes
One more step)

2022-08-05 10:22 UTC, A-Ostrovnyy commented on README.md
> +master
I think this must be deleted)

2022-08-05 10:22 UTC, A-Ostrovnyy commented on README.md
> +master
I think this must be deleted too)

2022-08-05 10:24 UTC, A-Ostrovnyy commented on README.md
> +Dasha
Those branch names must be deleted too

2022-08-14 13:15 UTC, closed without merging