pull request
kottans/mock-repo pull request #939
Opened 2022-08-04 17:07 UTC by Oberiin

2022-08-05 11:28 UTC, A-Ostrovnyy commented
One of the main rules of this PR is don't touch the changes of other students, Please restore changes from other students and add just yours :grinning: 
[Use this command](https://git-scm.com/docs/git-revert) to restore changes

2022-08-05 17:36 UTC, Oberiin commented
Lol, sorry, I'll restore changes.

Thanks!

2022-08-11 17:30 UTC, suchov commented
Tricky task, huh?

2022-08-11 18:53 UTC, suchov requested changes

2022-08-11 18:53 UTC, suchov commented on README.md
> -
no need for this from your IDE I assume

2022-08-11 18:53 UTC, suchov commented on README.md
> -Hello!
is it on purpose?

2022-08-15 05:36 UTC, closed without merging