Tab first branch
kottans/mock-repo pull request #956
Opened 2022-08-05 20:23 UTC by Tabermory

Hope I`m doing right)

2022-08-06 14:20 UTC, artem-trubin commented
Hey, there are a lot of different changes here. Check `Files changed` tab to make sure only your changes are there. Remove those `<<<<<<< HEAD` and stuff like this.

2022-08-11 18:49 UTC, suchov requested changes

2022-08-11 18:49 UTC, suchov commented on README.md
> +<<<<<<< HEAD
this is part of the conflict resolving, should be deleted

2022-08-11 18:49 UTC, suchov commented on README.md
> +<<<<<<< HEAD
This one too...

2022-08-11 18:49 UTC, suchov commented on README.md
> -
no need for empty line deletion

2022-08-15 19:51 UTC, closed without merging