My first Pull Request
kottans/mock-repo pull request #971
Opened 2022-08-06 21:36 UTC by ElenaRiabova

Stage 0. Git та GitHub (6)

2022-08-10 13:46 UTC, suchov commented
It looks like too many changes @ElenaRiabova maybe your IDE configuration, can you check it in the "Files changed" folder?

2022-08-10 15:58 UTC, ElenaRiabova commented
Can you please explain more about what I should do in the tab "Files changed"?
I made 4 commits because I got message that my file wasn't up to date

2022-08-11 08:17 UTC, suchov commented
Yeh, you have pretty much the same issue as in this PR https://github.com/kottans/mock-repo/pull/1014
Hope the answers in it will help, LMK if it's still confusing.

2022-08-11 18:46 UTC, suchov requested changes

2022-08-11 18:46 UTC, suchov commented on README.md
> +# ,,,^.\_.^,,,
remove extra lines editing

2022-08-11 18:46 UTC, suchov commented on README.md
> +thanks for the awesome course!
like this one too

2022-08-11 22:00 UTC, ElenaRiabova commented
> Yeh, you have pretty much the same issue as in this PR #1014 Hope the answers in it will help, LMK if it's still confusing.

I see all the changes but I can't edit them. I don't get the massage about merge conflict or see them in my file

2022-08-12 21:45 UTC, ElenaRiabova commented
It's getting out fo control, I'm closing this PR and starting anew.
Obviously, I don't have enough experience to fix/reverse/delete my mistakes now, maybe later I'll understand what went wrong

2022-08-12 21:45 UTC, closed without merging